name: offline-search

services:
  node-0:
    build:
      context: ../
      dockerfile: headless.Dockerfile
    environment:
      HOST: "node-0"
      NODE_ID: "00000000"
      P2P_PORT: "9400"
      CONTENT_PORT: "8080"
      OBSERVER_ADDRESS: "visualizer:80"
    ports:
      - "8080:8080"
  node-1:
    build:
      context: ../
      dockerfile: headless.Dockerfile
    environment:
      HOST: "node-1"
      NODE_ID: "ffffffff"
      BUDDY_NODE: "00000000:node-0:9400"
      P2P_PORT: "9400"
      CONTENT_PORT: "8080"
      OBSERVER_ADDRESS: "visualizer:80"
    ports:
      - "8081:8080"
  visualizer:
    build:
      context: ../
      dockerfile: visualizer.Dockerfile
    ports:
      - "8082:80"
