name: rangefinder

services:
  node-0:
    build:
      context: ../
      dockerfile: headless.Dockerfile
    environment:
      HOST: "node-0"
      NODE_ID: "00000000"
      P2P_PORT: "9400"
      CONTENT_PORT: "8080"
      EXTERNAL_CONTENT_URL: "http://localhost:8080/"
      OBSERVER_ADDRESS: "visualizer:80"
    ports:
      - "8080:8080"
  node-1:
    build:
      context: ../
      dockerfile: headless.Dockerfile
    environment:
      HOST: "node-1"
      NODE_ID: "ffffffff"
      BUDDY_NODE: "00000000:node-0:9400"
      P2P_PORT: "9400"
      CONTENT_PORT: "8080"
      EXTERNAL_CONTENT_URL: "http://localhost:8081/"
      OBSERVER_ADDRESS: "visualizer:80"
    ports:
      - "8081:8080"
  node-2:
    build:
      context: ../
      dockerfile: headless.Dockerfile
    environment:
      HOST: "node-2"
      NODE_ID: "aaaaaaaa"
      BUDDY_NODE: "00000000:node-0:9400"
      P2P_PORT: "9400"
      CONTENT_PORT: "8080"
      EXTERNAL_CONTENT_URL: "http://localhost:8082/"
      OBSERVER_ADDRESS: "visualizer:80"
    ports:
      - "8082:8080"
  node-3:
    build:
      context: ../
      dockerfile: headless.Dockerfile
    environment:
      HOST: "node-3"
      NODE_ID: "55555555"
      BUDDY_NODE: "aaaaaaaa:node-0:9400"
      P2P_PORT: "9400"
      CONTENT_PORT: "8080"
      EXTERNAL_CONTENT_URL: "http://localhost:8083/"
      OBSERVER_ADDRESS: "visualizer:80"
    ports:
      - "8083:8080"
  cli-0:
    build:
      context: ../
      dockerfile: cli.Dockerfile
    environment:
      HOST: "cli-0"
      OBSERVER_ADDRESS: "visualizer:80"
  cli-1:
    build:
      context: ../
      dockerfile: cli.Dockerfile
    environment:
      HOST: "cli-1"
      OBSERVER_ADDRESS: "visualizer:80"
  visualizer:
    build:
      context: ../
      dockerfile: visualizer.Dockerfile
    ports:
      - "9000:80"
