apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: rangefinder
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-rangefinder
  namespace: rangefinder
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator
  namespace: rangefinder
subjects:
  - kind: ServiceAccount
    name: operator
    apiGroup: ""
roleRef:
  kind: Role
  name: access-rangefinder
  apiGroup: rbac.authorization.k8s.io
