apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: rangefinder
  labels:
    app: operator
spec:
  selector:
    matchLabels:
      app: operator
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - worker
      serviceAccountName: operator
      containers:
        - name: operator
          image: images.sourcegrade.org/rangefinder/operator:latest
          env:
            - name: VISUALIZER_URL
              value: "visualizer"
