apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer
  namespace: rangefinder
  labels:
    app: visualizer
spec:
  selector:
    matchLabels:
      app: visualizer
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: visualizer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - worker
      containers:
        - name: visualizer
          image: images.sourcegrade.org/rangefinder/visualizer:latest
