apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer
  namespace: offline-search
  labels:
    app: visualizer
spec:
  selector:
    matchLabels:
      app: visualizer
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: visualizer
    spec:
      containers:
        - name: visualizer
          image: images.sourcegrade.org/offline-search/visualizer:latest
